# Generated by Django 2.2.3 on 2020-06-08 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
    ]
